/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_joshuad_hypnos_trayicon_LinuxTrayIcon */

#ifndef _Included_net_joshuad_hypnos_trayicon_LinuxTrayIcon
#define _Included_net_joshuad_hypnos_trayicon_LinuxTrayIcon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_joshuad_hypnos_trayicon_LinuxTrayIcon
 * Method:    initTrayIcon
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_joshuad_hypnos_trayicon_LinuxTrayIcon_initTrayIcon
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_joshuad_hypnos_trayicon_LinuxTrayIcon
 * Method:    showTrayIcon
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_joshuad_hypnos_trayicon_LinuxTrayIcon_showTrayIcon
  (JNIEnv *, jobject);

/*
 * Class:     net_joshuad_hypnos_trayicon_LinuxTrayIcon
 * Method:    hideTrayIcon
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_joshuad_hypnos_trayicon_LinuxTrayIcon_hideTrayIcon
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
